### ISSUE TITLE
Missing <article> tag or extraneous  article closing tag

### ISSUE THREAD

**Issue by jgmac1106** [cleverdevil/Known-Reviews#6]
Check out: http://quickthoughts.jgregorymcverry.com/content/watching/ I see an errant closing article tag

**Comment by cleverdevil** [comment]
Is this for Reviews or Watching?

I looked at the page referenced above and didn't see any missing markup and also checked the code for Watching and the template appears to be correct, with an open/close match for article tags.

**Comment by jgmac1106** [comment]
yeah closing this, I swore last night I only saw the closing tag, took a screenshot. Strange. Nothing to see here.
